config/routes.rb
ManipalProject::Application.routes.draw do
  resources :musics
  resources :users
  resources :projects
  resources :sessions, :only => [:new, :create, :destroy]
  resources "contacts", only: [:new, :create]

      root            :to => 'pages#home'
  match '/home',      :to => 'pages#home', via: [:get, :post]
  match '/projects',  :to => 'projects#index', via: [:get, :post]
  match '/skills',    :to => 'pages#skills', via: [:get, :post]
  match '/lifestyle', :to => 'musics#index', via: [:get, :post]
  match '/cv',        :to => 'pages#cv', via: [:get, :post]
  match '/contacts',  :to => 'contacts#new', via: 'get'
  match '/about',     :to => 'pages#about', via: [:get, :post]
  match '/signup',    :to => 'users#new', via: [:get, :post]
  match '/signin',    :to => 'sessions#new', via: [:get, :post]
  match '/signout',   :to => 'sessions#destroy', via: [:delete]
end

app/models/music.rb
# == Schema Information
#
# Table name: musics
#
#  id          :integer          not null, primary key
#  nom         :string(255)
#  compositeur :string(255)
#  path        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  altimg      :string(255)
#

require 'digest'
class Music < ActiveRecord::Base
	def create
		Music.create(music_params)
	end
	private
	def music_params
		params.require(:music).permit(:nom, :compositeur, :path, :altimg)
	end

	validates 	:compositeur, :presence => true,
				      :length => { :minimum => 3 }
	validates 	:nom, :presence => true,
				      :length => { :minimum => 3 },
				      :uniqueness => true
	validates 	:path, :presence => true
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
    before_action :set_music, only: [:show, :edit, :update, :destroy]

  # GET /musics
  # GET /musics.json
  def index
    @title = "LifeStyle"
    @subtitle = "My LifeStyle"
    @musics = Music.all
  end

  # GET /Musics/1
  # GET /Musics/1.json
  def show
    @title = @music.nom
    @subtitle = @music.nom
  end

  # GET /Musics/new
  def new
    @title = "New Music"
    @subtitle = "Create New Music"
    @music = Music.new
  end

  # GET /Musics/1/edit
  def edit
    @title = "Editing Music"
    @subtitle = "Editing Music..."
  end

  # POST /Musics
  # POST /Musics.json
  def create
    @music = Music.new(music_params)
    if @music.save
      flash[:success] = "Music created."
      redirect_to @music
      # format.html { redirect_to @project, notice: 'Project was successfully created.' }
      # format.json { render action: 'show', status: :created, location: @project }
    else
      flash[:error] = "Music not created."
      render 'new'
      # format.html { render action: 'new' }
      # format.json { render json: @project.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    @music = Music.find(params[:id])
    if @music.update_attributes(music_params)
      redirect_to musics_path
      flash[:success] = "Music Updated."
    else
      @title = "Editing Music..."
      render 'edit'
      flash[:error] = "Music not Updated."
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @music.destroy
    respond_to do |format|
      format.html { redirect_to musics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def music_params
      params.require(:music).permit(:nom, :compositeur, :path, :altimg)
    end
end

app/helpers/musics_helper.rb
module MusicsHelper
	def hasVideo(music)
		if music.path.split('.')[music.path.split('.').length - 1] == "mp4"
			return true
		else
			return false
		end
	end
end

app/views/musics/_form.html.erb
<%= form_for(@music) do |f| %>
  <% if @music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
      <% @music.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :compositeur %><br>
    <%= f.text_field :compositeur %>
  </div>
  <div class="field">
    <%= f.label :path %><br>
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :altimg %><br>
    <%= f.text_field :altimg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/musics/_music.html.erb
<div class="music round">
	<div class="music_p">
	  <div class="music_title"><%= music.nom + " - " + music.compositeur %></div>	
	</div>
	<hr>
	<div class="music_p">
		<% if hasVideo(music) %>
		<video width="320" height="240" controls>
		  <source src="/videos/<%= music.path %>" type="video/mp4">
		  <object src="/videos/<%= music.path %>" width="320" height="240">
		    <embed src=src="/videos/<%= music.path %>" width="320" height="240">
		  </object> 
		</video>
		<% else %>
		<div><img src="/musics/img/<%= music.altimg %>" width="300" /></div>
		<div><audio controls>
		  <source src="/musics/<%= music.path %>" type="audio/mpeg">
		  <embed height="50" width="300" src="/musics/<%= music.path %>">
		</audio></div>
		<% end %>
		<p><%= link_to "Read more...", music %></p>
	</div>
</div>

app/views/musics/edit.html.erb
<%= render 'pages/viewchange' %>

<%= render 'form' %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>
<% if current_user.admin? %>
  | <%= link_to "Delete", @music, :method => :delete, :confirm => "Are you sure ?",
                                :nom => "Delete #{@music.nom}" %>
  <% end %>

app/views/musics/index.html.erb
<%= render 'pages/viewchange' %>
<%= image_tag "/images/separator2.png", :class => "separator" %>

<div class="musics">
  <%= render @musics %>
</div>

<br>
<% if current_user != nil && current_user.admin? %>
<%= link_to 'New Music', new_music_path %>
<% end %>

app/views/musics/new.html.erb
<%= render 'pages/viewchange' %>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/musics/show.html.erb
<%= render 'pages/viewchange' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @music.nom %>
</p>

<p>
  <strong>Compositor:</strong>
  <%= @music.compositeur %>
</p>

<video width="320" height="240" controls>
	<source src="/videos/<%= @music.path %>" type="video/mp4">
</video>

<% if current_user != nil && current_user.admin? %>
<%= link_to 'Edit', edit_music_path(@music) %> |
<% end %>
<%= link_to 'Back', musics_path %>