config/routes.rb
ManipalProject::Application.routes.draw do
  resources :musics
  resources :users
  resources :projects
  resources :sessions, :only => [:new, :create, :destroy]
  resources "contacts", only: [:new, :create]

      root            :to => 'pages#home'
  match '/home',      :to => 'pages#home', via: [:get, :post]
  match '/projects',  :to => 'projects#index', via: [:get, :post]
  match '/skills',    :to => 'pages#skills', via: [:get, :post]
  match '/lifestyle', :to => 'musics#index', via: [:get, :post]
  match '/cv',        :to => 'pages#cv', via: [:get, :post]
  match '/contacts',  :to => 'contacts#new', via: 'get'
  match '/about',     :to => 'pages#about', via: [:get, :post]
  match '/signup',    :to => 'users#new', via: [:get, :post]
  match '/signin',    :to => 'sessions#new', via: [:get, :post]
  match '/signout',   :to => 'sessions#destroy', via: [:delete]
end

app/views/layouts/_canvas.html.erb
<canvas id="canvas-cubic-nav"></canvas>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <% if key.to_s == "error" %>
    <div class="ui-state-error ui-corner-all" style="padding: 0 .9em;">
      <span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em; margin-top: .2em"></span>
      <strong>Hey!</strong>
      <%= content_tag('p', value) %>
    </div>
  <% else %>
    <div class="ui-state-highlight ui-corner-all" style="padding: 0 .9em;">
      <span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em; margin-top: .2em"></span>
      <strong>Hey!</strong>
      <%= content_tag('p', value) %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round footer">
    <ul>
      <li><%= link_to "About me", about_path, :onclick => "UIstartAnimation()" %></li>
      <li><%= link_to "Curriculum Vitae", cv_path, :onclick => "UIstartAnimation()" %></li>
      <li><%= link_to "Contact me", contacts_path, :onclick => "UIstartAnimation()" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= logo %>
  <nav class="round header">
    <ul>
      <li><%= link_to "Home", root_path, :onclick => "UIstartAnimation()" %></li>
      <% if signed_in? %>
        <li><%= link_to "Profile", current_user, :onclick => "UIstartAnimation()" %></li>
      <% end %>
        <li><%= link_to "Projects", projects_path, :onclick => "UIstartAnimation()" %></li>
        <li><%= link_to "Skills", skills_path, :onclick => "UIstartAnimation()" %></li>
        <li><%= link_to "Lifestyle", lifestyle_path, :onclick => "UIstartAnimation()" %></li>
      <% if signed_in? %>
        <li><%= link_to "Sign out", signout_path, :method => :delete, :onclick => "UIstartAnimation()" %></li>
      <% else %>
        <li><%= link_to "Sign In", signin_path, :onclick => "UIstartAnimation()" %></li>
      <% end %>
    </ul>
    <% if current_user != nil && current_user.admin? %>
    <ul>
      <!-- <li><%= link_to "Users", users_path, :onclick => "UIstartAnimation()" %></li> -->
    </ul>
    <% end %>
  </nav>
</header>

app/views/layouts/_javascripts.erb
<%= javascript_include_tag "jquery-1.10.2.js", "application" %>
<%= javascript_include_tag "jquery-1.10.2.js", "jquery-ui-1.10.4.custom.min.js" %>
<%= javascript_include_tag "glMatrix-0.9.5.min.js" %>
<%= javascript_include_tag "webgl-utils.js" %>
<%= javascript_include_tag "myScriptCubicNav.js" %>
<%= javascript_include_tag "myScript.js" %>
<%= javascript_include_tag "modernizr.custom.js" %>
<%= javascript_include_tag "toucheffects.js" %>
<!--******************************-->
<!--** WebGL framents en vertex **-->
<!--******************************-->
<script id="shader-fs" type="x-shader/x-fragment">
  precision mediump float;
  varying vec2 vTextureCoord;
  uniform sampler2D uSampler;
  void main(void) {
      gl_FragColor = texture2D(uSampler, vec2(vTextureCoord.s, vTextureCoord.t));
  }
</script>
<script id="shader-vs" type="x-shader/x-vertex">
  attribute vec3 aVertexPosition;
  attribute vec2 aTextureCoord;
  uniform mat4 uMVMatrix;
  uniform mat4 uPMatrix;
  varying vec2 vTextureCoord;
  void main(void) {
      gl_Position = uPMatrix * uMVMatrix * vec4(aVertexPosition, 1.0);
      vTextureCoord = aTextureCoord;
  }
</script>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'jquery-ui-1.10.4.custom.min', :media => 'screen' %>
<%= stylesheet_link_tag 'grid/default', :media => 'screen' %>
<%= stylesheet_link_tag 'grid/component', :media => 'screen' %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'myCanvas', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= render 'layouts/javascripts' %>
  </head>
  <body onload="init();" onResize="onWindowResize();">
    <div id="canvasdiv">
      <%= render 'layouts/canvas' %>
    </div>
    <div id="mainContainer" class="container">
      <div class="container">
        <%= render 'layouts/header' %>
        <section class="round">
          <%= render 'layouts/flash' %>
          <h1><%= subtitle %></h1>
          <%= yield %>
        </section>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </body>
</html>